/* Mega Evolution — Ascended Heroes (me02.5) · 295 cards
   images + TCGplayer USD prices via TCGdex, snapshot 2026-06-24 */
window.TCG_COLLECTIONS = window.TCG_COLLECTIONS || [];
window.TCG_COLLECTIONS.push(
{
 "id": "ascended-heroes",
 "name": "Ascended Heroes",
 "tagline": "Mega Evolution — Ascended Heroes · full 295-card master set",
 "accent": "#34d0d6",
 "accent2": "#7c83ff",
 "cards": [
  {
   "id": "ah-001",
   "name": "Erika's Oddish",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "1/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/001/high.webp"
  },
  {
   "id": "ah-002",
   "name": "Erika's Gloom",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "2/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/002/high.webp"
  },
  {
   "id": "ah-003",
   "name": "Erika's Vileplume ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "3/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.84,
   "priceText": "$0.84",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/003/high.webp"
  },
  {
   "id": "ah-004",
   "name": "Erika's Bellsprout",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "4/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/004/high.webp"
  },
  {
   "id": "ah-005",
   "name": "Erika's Weepinbell",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "5/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/005/high.webp"
  },
  {
   "id": "ah-006",
   "name": "Erika's Victreebel",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "6/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/006/high.webp"
  },
  {
   "id": "ah-007",
   "name": "Erika's Tangela",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "7/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.14,
   "priceText": "$0.14",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/007/high.webp"
  },
  {
   "id": "ah-008",
   "name": "Chikorita",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "8/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/008/high.webp"
  },
  {
   "id": "ah-009",
   "name": "Bayleef",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "9/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/009/high.webp"
  },
  {
   "id": "ah-010",
   "name": "Mega Meganium ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "10/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.23,
   "priceText": "$1.23",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/010/high.webp"
  },
  {
   "id": "ah-011",
   "name": "Wurmple",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "11/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/011/high.webp"
  },
  {
   "id": "ah-012",
   "name": "Silcoon",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "12/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/012/high.webp"
  },
  {
   "id": "ah-013",
   "name": "Beautifly",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "13/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/013/high.webp"
  },
  {
   "id": "ah-014",
   "name": "Cascoon",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "14/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/014/high.webp"
  },
  {
   "id": "ah-015",
   "name": "Dustox",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "15/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.05,
   "priceText": "$0.05",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/015/high.webp"
  },
  {
   "id": "ah-016",
   "name": "Budew",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "16/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.14,
   "priceText": "$0.14",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/016/high.webp"
  },
  {
   "id": "ah-017",
   "name": "Grubbin",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "17/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.03,
   "priceText": "$0.03",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/017/high.webp"
  },
  {
   "id": "ah-018",
   "name": "Team Rocket's Tarountula",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "18/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/018/high.webp"
  },
  {
   "id": "ah-019",
   "name": "Team Rocket's Spidops",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "19/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.21,
   "priceText": "$0.21",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/019/high.webp"
  },
  {
   "id": "ah-020",
   "name": "Charmander",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "20/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/020/high.webp"
  },
  {
   "id": "ah-021",
   "name": "Charmeleon",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "21/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.21,
   "priceText": "$0.21",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/021/high.webp"
  },
  {
   "id": "ah-022",
   "name": "Mega Charizard Y ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "22/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 9.13,
   "priceText": "$9.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/022/high.webp"
  },
  {
   "id": "ah-023",
   "name": "Ethan's Slugma",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "23/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/023/high.webp"
  },
  {
   "id": "ah-024",
   "name": "Ethan's Magcargo",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "24/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/024/high.webp"
  },
  {
   "id": "ah-025",
   "name": "Entei",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "25/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.21,
   "priceText": "$0.21",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/025/high.webp"
  },
  {
   "id": "ah-026",
   "name": "Ethan's Ho-Oh ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "26/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.66,
   "priceText": "$0.66",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/026/high.webp"
  },
  {
   "id": "ah-027",
   "name": "Numel",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "27/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/027/high.webp"
  },
  {
   "id": "ah-028",
   "name": "Camerupt",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "28/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/028/high.webp"
  },
  {
   "id": "ah-029",
   "name": "Tepig",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "29/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/029/high.webp"
  },
  {
   "id": "ah-030",
   "name": "Pignite",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "30/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/030/high.webp"
  },
  {
   "id": "ah-031",
   "name": "Mega Emboar ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "31/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.78,
   "priceText": "$0.78",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/031/high.webp"
  },
  {
   "id": "ah-032",
   "name": "N's Darumaka",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "32/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/032/high.webp"
  },
  {
   "id": "ah-033",
   "name": "N's Darmanitan",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "33/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/033/high.webp"
  },
  {
   "id": "ah-034",
   "name": "Salandit",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "34/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/034/high.webp"
  },
  {
   "id": "ah-035",
   "name": "Salazzle",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "35/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/035/high.webp"
  },
  {
   "id": "ah-036",
   "name": "Scorbunny",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "36/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/036/high.webp"
  },
  {
   "id": "ah-037",
   "name": "Raboot",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "37/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/037/high.webp"
  },
  {
   "id": "ah-038",
   "name": "Cinderace ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "38/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.75,
   "priceText": "$0.75",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/038/high.webp"
  },
  {
   "id": "ah-039",
   "name": "Psyduck",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "39/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.32,
   "priceText": "$0.32",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/039/high.webp"
  },
  {
   "id": "ah-040",
   "name": "Golduck",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "40/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/040/high.webp"
  },
  {
   "id": "ah-041",
   "name": "Totodile",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "41/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/041/high.webp"
  },
  {
   "id": "ah-042",
   "name": "Croconaw",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "42/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/042/high.webp"
  },
  {
   "id": "ah-043",
   "name": "Mega Feraligatr ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "43/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.37,
   "priceText": "$1.37",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/043/high.webp"
  },
  {
   "id": "ah-044",
   "name": "Sneasel",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "44/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/044/high.webp"
  },
  {
   "id": "ah-045",
   "name": "Weavile",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "45/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/045/high.webp"
  },
  {
   "id": "ah-046",
   "name": "Snorunt",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "46/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.27,
   "priceText": "$0.27",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/046/high.webp"
  },
  {
   "id": "ah-047",
   "name": "Mega Froslass ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "47/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 4.1,
   "priceText": "$4.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/047/high.webp"
  },
  {
   "id": "ah-048",
   "name": "Regice ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "48/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.67,
   "priceText": "$0.67",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/048/high.webp"
  },
  {
   "id": "ah-049",
   "name": "N's Vanillite",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "49/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/049/high.webp"
  },
  {
   "id": "ah-050",
   "name": "N's Vanillish",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "50/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/050/high.webp"
  },
  {
   "id": "ah-051",
   "name": "N's Vanilluxe",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "51/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/051/high.webp"
  },
  {
   "id": "ah-052",
   "name": "Snom",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "52/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/052/high.webp"
  },
  {
   "id": "ah-053",
   "name": "Frosmoth",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "53/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/053/high.webp"
  },
  {
   "id": "ah-054",
   "name": "Glastrier",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "54/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/054/high.webp"
  },
  {
   "id": "ah-055",
   "name": "Pikachu",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "55/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.28,
   "priceText": "$0.28",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/055/high.webp"
  },
  {
   "id": "ah-056",
   "name": "Raichu",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "56/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/056/high.webp"
  },
  {
   "id": "ah-057",
   "name": "Pikachu ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "57/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 3.41,
   "priceText": "$3.41",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/057/high.webp"
  },
  {
   "id": "ah-058",
   "name": "Voltorb ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "58/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.69,
   "priceText": "$0.69",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/058/high.webp"
  },
  {
   "id": "ah-059",
   "name": "Tynamo",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "59/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/059/high.webp"
  },
  {
   "id": "ah-060",
   "name": "Eelektrik",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "60/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/060/high.webp"
  },
  {
   "id": "ah-061",
   "name": "Mega Eelektross ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "61/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.87,
   "priceText": "$0.87",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/061/high.webp"
  },
  {
   "id": "ah-062",
   "name": "Stunfisk",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "62/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/062/high.webp"
  },
  {
   "id": "ah-063",
   "name": "Helioptile",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "63/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.14,
   "priceText": "$0.14",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/063/high.webp"
  },
  {
   "id": "ah-064",
   "name": "Heliolisk",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "64/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/064/high.webp"
  },
  {
   "id": "ah-065",
   "name": "Charjabug",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "65/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/065/high.webp"
  },
  {
   "id": "ah-066",
   "name": "Vikavolt",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "66/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/066/high.webp"
  },
  {
   "id": "ah-067",
   "name": "Tapu Koko",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "67/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/067/high.webp"
  },
  {
   "id": "ah-068",
   "name": "Hop's Pincurchin ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "68/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.54,
   "priceText": "$0.54",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/068/high.webp"
  },
  {
   "id": "ah-069",
   "name": "Iono's Tadbulb",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "69/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/069/high.webp"
  },
  {
   "id": "ah-070",
   "name": "Iono's Bellibolt ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "70/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.64,
   "priceText": "$0.64",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/070/high.webp"
  },
  {
   "id": "ah-071",
   "name": "Iono's Wattrel",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "71/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/071/high.webp"
  },
  {
   "id": "ah-072",
   "name": "Iono's Kilowattrel",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "72/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/072/high.webp"
  },
  {
   "id": "ah-073",
   "name": "Miraidon ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "73/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.62,
   "priceText": "$0.62",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/073/high.webp"
  },
  {
   "id": "ah-074",
   "name": "Clefairy",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "74/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.25,
   "priceText": "$0.25",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/074/high.webp"
  },
  {
   "id": "ah-075",
   "name": "Clefable",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "75/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/075/high.webp"
  },
  {
   "id": "ah-076",
   "name": "Lillie's Clefairy ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "76/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.46,
   "priceText": "$1.46",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/076/high.webp"
  },
  {
   "id": "ah-077",
   "name": "Team Rocket's Exeggcute",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "77/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/077/high.webp"
  },
  {
   "id": "ah-078",
   "name": "Team Rocket's Exeggutor",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "78/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/078/high.webp"
  },
  {
   "id": "ah-079",
   "name": "Team Rocket's Mewtwo ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "79/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.22,
   "priceText": "$1.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/079/high.webp"
  },
  {
   "id": "ah-080",
   "name": "Togepi",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "80/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/080/high.webp"
  },
  {
   "id": "ah-081",
   "name": "Togetic",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "81/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/081/high.webp"
  },
  {
   "id": "ah-082",
   "name": "Togekiss",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "82/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/082/high.webp"
  },
  {
   "id": "ah-083",
   "name": "Marill",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "83/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/083/high.webp"
  },
  {
   "id": "ah-084",
   "name": "Azumarill ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "84/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.8,
   "priceText": "$0.80",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/084/high.webp"
  },
  {
   "id": "ah-085",
   "name": "Misdreavus",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "85/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/085/high.webp"
  },
  {
   "id": "ah-086",
   "name": "Mismagius",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "86/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/086/high.webp"
  },
  {
   "id": "ah-087",
   "name": "Ralts",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "87/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/087/high.webp"
  },
  {
   "id": "ah-088",
   "name": "Kirlia",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "88/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/088/high.webp"
  },
  {
   "id": "ah-089",
   "name": "Mega Gardevoir ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "89/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.67,
   "priceText": "$0.67",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/089/high.webp"
  },
  {
   "id": "ah-090",
   "name": "Shuppet",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "90/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/090/high.webp"
  },
  {
   "id": "ah-091",
   "name": "Banette",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "91/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.05,
   "priceText": "$0.05",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/091/high.webp"
  },
  {
   "id": "ah-092",
   "name": "Rotom",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "92/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/092/high.webp"
  },
  {
   "id": "ah-093",
   "name": "Swirlix",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "93/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/093/high.webp"
  },
  {
   "id": "ah-094",
   "name": "Slurpuff",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "94/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/094/high.webp"
  },
  {
   "id": "ah-095",
   "name": "Hop's Phantump",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "95/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/095/high.webp"
  },
  {
   "id": "ah-096",
   "name": "Hop's Trevenant",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "96/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/096/high.webp"
  },
  {
   "id": "ah-097",
   "name": "Team Rocket's Mimikyu",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "97/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/097/high.webp"
  },
  {
   "id": "ah-098",
   "name": "Spectrier",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "98/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.26,
   "priceText": "$0.26",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/098/high.webp"
  },
  {
   "id": "ah-099",
   "name": "Munkidori",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "99/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/099/high.webp"
  },
  {
   "id": "ah-100",
   "name": "Team Rocket's Diglett",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "100/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/100/high.webp"
  },
  {
   "id": "ah-101",
   "name": "Team Rocket's Dugtrio",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "101/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/101/high.webp"
  },
  {
   "id": "ah-102",
   "name": "Hitmontop",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "102/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/102/high.webp"
  },
  {
   "id": "ah-103",
   "name": "Meditite",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "103/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/103/high.webp"
  },
  {
   "id": "ah-104",
   "name": "Medicham",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "104/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/104/high.webp"
  },
  {
   "id": "ah-105",
   "name": "Lunatone",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "105/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/105/high.webp"
  },
  {
   "id": "ah-106",
   "name": "Solrock",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "106/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/106/high.webp"
  },
  {
   "id": "ah-107",
   "name": "Regirock ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "107/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.61,
   "priceText": "$0.61",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/107/high.webp"
  },
  {
   "id": "ah-108",
   "name": "Groudon",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "108/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/108/high.webp"
  },
  {
   "id": "ah-109",
   "name": "Cynthia's Gible",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "109/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/109/high.webp"
  },
  {
   "id": "ah-110",
   "name": "Cynthia's Gabite",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "110/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.21,
   "priceText": "$0.21",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/110/high.webp"
  },
  {
   "id": "ah-111",
   "name": "Cynthia's Garchomp ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "111/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.9,
   "priceText": "$0.90",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/111/high.webp"
  },
  {
   "id": "ah-112",
   "name": "Riolu",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "112/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/112/high.webp"
  },
  {
   "id": "ah-113",
   "name": "Mega Lucario ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "113/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.04,
   "priceText": "$1.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/113/high.webp"
  },
  {
   "id": "ah-114",
   "name": "Stunfisk ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "114/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.63,
   "priceText": "$0.63",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/114/high.webp"
  },
  {
   "id": "ah-115",
   "name": "Pancham",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "115/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.04,
   "priceText": "$0.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/115/high.webp"
  },
  {
   "id": "ah-116",
   "name": "Mega Hawlucha ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "116/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.92,
   "priceText": "$0.92",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/116/high.webp"
  },
  {
   "id": "ah-117",
   "name": "Carbink",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "117/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.04,
   "priceText": "$0.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/117/high.webp"
  },
  {
   "id": "ah-118",
   "name": "Rolycoly",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "118/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.04,
   "priceText": "$0.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/118/high.webp"
  },
  {
   "id": "ah-119",
   "name": "Carkol",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "119/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/119/high.webp"
  },
  {
   "id": "ah-120",
   "name": "Coalossal",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "120/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/120/high.webp"
  },
  {
   "id": "ah-121",
   "name": "Koraidon ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "121/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.71,
   "priceText": "$0.71",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/121/high.webp"
  },
  {
   "id": "ah-122",
   "name": "Okidogi",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "122/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/122/high.webp"
  },
  {
   "id": "ah-123",
   "name": "Gastly",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "123/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/123/high.webp"
  },
  {
   "id": "ah-124",
   "name": "Haunter",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "124/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/124/high.webp"
  },
  {
   "id": "ah-125",
   "name": "Mega Gengar ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "125/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 3.24,
   "priceText": "$3.24",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/125/high.webp"
  },
  {
   "id": "ah-126",
   "name": "Team Rocket's Murkrow",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "126/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/126/high.webp"
  },
  {
   "id": "ah-127",
   "name": "Team Rocket's Honchkrow",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "127/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.24,
   "priceText": "$0.24",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/127/high.webp"
  },
  {
   "id": "ah-128",
   "name": "Poochyena",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "128/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/128/high.webp"
  },
  {
   "id": "ah-129",
   "name": "Mightyena",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "129/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.04,
   "priceText": "$0.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/129/high.webp"
  },
  {
   "id": "ah-130",
   "name": "Galarian Zigzagoon",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "130/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.1,
   "priceText": "$0.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/130/high.webp"
  },
  {
   "id": "ah-131",
   "name": "Galarian Linoone",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "131/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/131/high.webp"
  },
  {
   "id": "ah-132",
   "name": "Galarian Obstagoon",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "132/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/132/high.webp"
  },
  {
   "id": "ah-133",
   "name": "Cynthia's Spiritomb",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "133/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/133/high.webp"
  },
  {
   "id": "ah-134",
   "name": "Scraggy",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "134/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/134/high.webp"
  },
  {
   "id": "ah-135",
   "name": "Mega Scrafty ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "135/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.04,
   "priceText": "$1.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/135/high.webp"
  },
  {
   "id": "ah-136",
   "name": "N's Zorua",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "136/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/136/high.webp"
  },
  {
   "id": "ah-137",
   "name": "N's Zoroark ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "137/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.0,
   "priceText": "$1.00",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/137/high.webp"
  },
  {
   "id": "ah-138",
   "name": "Vullaby",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "138/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.04,
   "priceText": "$0.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/138/high.webp"
  },
  {
   "id": "ah-139",
   "name": "Mandibuzz ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "139/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.63,
   "priceText": "$0.63",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/139/high.webp"
  },
  {
   "id": "ah-140",
   "name": "Pangoro",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "140/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/140/high.webp"
  },
  {
   "id": "ah-141",
   "name": "Hoopa",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "141/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/141/high.webp"
  },
  {
   "id": "ah-142",
   "name": "Fezandipiti ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "142/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 4.39,
   "priceText": "$4.39",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/142/high.webp"
  },
  {
   "id": "ah-143",
   "name": "Pecharunt",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "143/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/143/high.webp"
  },
  {
   "id": "ah-144",
   "name": "Mawile",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "144/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/144/high.webp"
  },
  {
   "id": "ah-145",
   "name": "Registeel ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "145/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.63,
   "priceText": "$0.63",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/145/high.webp"
  },
  {
   "id": "ah-146",
   "name": "Pawniard",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "146/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.04,
   "priceText": "$0.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/146/high.webp"
  },
  {
   "id": "ah-147",
   "name": "Bisharp",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "147/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/147/high.webp"
  },
  {
   "id": "ah-148",
   "name": "Kingambit",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "148/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/148/high.webp"
  },
  {
   "id": "ah-149",
   "name": "Togedemaru ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "149/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.64,
   "priceText": "$0.64",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/149/high.webp"
  },
  {
   "id": "ah-150",
   "name": "Dratini",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "150/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.19,
   "priceText": "$0.19",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/150/high.webp"
  },
  {
   "id": "ah-151",
   "name": "Dragonair",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "151/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/151/high.webp"
  },
  {
   "id": "ah-152",
   "name": "Mega Dragonite ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "152/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 4.78,
   "priceText": "$4.78",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/152/high.webp"
  },
  {
   "id": "ah-153",
   "name": "Rayquaza",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "153/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.4,
   "priceText": "$0.40",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/153/high.webp"
  },
  {
   "id": "ah-154",
   "name": "N's Reshiram",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "154/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/154/high.webp"
  },
  {
   "id": "ah-155",
   "name": "N's Zekrom",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "155/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.25,
   "priceText": "$0.25",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/155/high.webp"
  },
  {
   "id": "ah-156",
   "name": "Noibat",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "156/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/156/high.webp"
  },
  {
   "id": "ah-157",
   "name": "Noivern",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "157/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.12,
   "priceText": "$0.12",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/157/high.webp"
  },
  {
   "id": "ah-158",
   "name": "Dreepy",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "158/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/158/high.webp"
  },
  {
   "id": "ah-159",
   "name": "Drakloak",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "159/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/159/high.webp"
  },
  {
   "id": "ah-160",
   "name": "Dragapult ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "160/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.32,
   "priceText": "$1.32",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/160/high.webp"
  },
  {
   "id": "ah-161",
   "name": "Team Rocket's Meowth",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "161/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.11,
   "priceText": "$0.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/161/high.webp"
  },
  {
   "id": "ah-162",
   "name": "Team Rocket's Kangaskhan ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "162/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.95,
   "priceText": "$0.95",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/162/high.webp"
  },
  {
   "id": "ah-163",
   "name": "Larry's Dunsparce",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "163/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/163/high.webp"
  },
  {
   "id": "ah-164",
   "name": "Larry's Dudunsparce ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "164/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.64,
   "priceText": "$0.64",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/164/high.webp"
  },
  {
   "id": "ah-165",
   "name": "Skitty",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "165/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/165/high.webp"
  },
  {
   "id": "ah-166",
   "name": "Delcatty",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "166/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/166/high.webp"
  },
  {
   "id": "ah-167",
   "name": "Zangoose ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "167/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.63,
   "priceText": "$0.63",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/167/high.webp"
  },
  {
   "id": "ah-168",
   "name": "Larry's Starly",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "168/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.04,
   "priceText": "$0.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/168/high.webp"
  },
  {
   "id": "ah-169",
   "name": "Larry's Staravia",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "169/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.03,
   "priceText": "$0.03",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/169/high.webp"
  },
  {
   "id": "ah-170",
   "name": "Larry's Staraptor",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "170/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/170/high.webp"
  },
  {
   "id": "ah-171",
   "name": "Fan Rotom",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "171/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/171/high.webp"
  },
  {
   "id": "ah-172",
   "name": "Mega Audino ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "172/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 1.01,
   "priceText": "$1.01",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/172/high.webp"
  },
  {
   "id": "ah-173",
   "name": "Larry's Rufflet",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "173/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/173/high.webp"
  },
  {
   "id": "ah-174",
   "name": "Larry's Braviary",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "174/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.06,
   "priceText": "$0.06",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/174/high.webp"
  },
  {
   "id": "ah-175",
   "name": "Larry's Komala",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "175/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/175/high.webp"
  },
  {
   "id": "ah-176",
   "name": "Drampa",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "176/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.05,
   "priceText": "$0.05",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/176/high.webp"
  },
  {
   "id": "ah-177",
   "name": "Hop's Cramorant",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "177/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/177/high.webp"
  },
  {
   "id": "ah-178",
   "name": "Terapagos",
   "variant": "Rare",
   "set": "Ascended Heroes",
   "number": "178/217",
   "year": 2026,
   "rarity": "Rare",
   "tier": 1,
   "price": 0.05,
   "priceText": "$0.05",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/178/high.webp"
  },
  {
   "id": "ah-179",
   "name": "Terapagos ex",
   "variant": "Double rare",
   "set": "Ascended Heroes",
   "number": "179/217",
   "year": 2026,
   "rarity": "Double rare",
   "tier": 1,
   "price": 0.68,
   "priceText": "$0.68",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/179/high.webp"
  },
  {
   "id": "ah-180",
   "name": "Acerola's Mischief",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "180/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/180/high.webp"
  },
  {
   "id": "ah-181",
   "name": "Air Balloon",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "181/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/181/high.webp"
  },
  {
   "id": "ah-182",
   "name": "Anthea & Concordia",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "182/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/182/high.webp"
  },
  {
   "id": "ah-183",
   "name": "Boss's Orders",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "183/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.23,
   "priceText": "$0.23",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/183/high.webp"
  },
  {
   "id": "ah-184",
   "name": "Buddy-Buddy Poffin",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "184/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.19,
   "priceText": "$0.19",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/184/high.webp"
  },
  {
   "id": "ah-185",
   "name": "Canari",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "185/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.21,
   "priceText": "$0.21",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/185/high.webp"
  },
  {
   "id": "ah-186",
   "name": "Counter Gain",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "186/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.14,
   "priceText": "$0.14",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/186/high.webp"
  },
  {
   "id": "ah-187",
   "name": "Fighting Gong",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "187/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/187/high.webp"
  },
  {
   "id": "ah-188",
   "name": "Forest of Vitality",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "188/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.21,
   "priceText": "$0.21",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/188/high.webp"
  },
  {
   "id": "ah-189",
   "name": "Glass Trumpet",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "189/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/189/high.webp"
  },
  {
   "id": "ah-190",
   "name": "Iris's Fighting Spirit",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "190/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.07,
   "priceText": "$0.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/190/high.webp"
  },
  {
   "id": "ah-191",
   "name": "Light Ball",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "191/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/191/high.webp"
  },
  {
   "id": "ah-192",
   "name": "Lillie's Determination",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "192/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.35,
   "priceText": "$0.35",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/192/high.webp"
  },
  {
   "id": "ah-193",
   "name": "Mega Signal",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "193/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.19,
   "priceText": "$0.19",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/193/high.webp"
  },
  {
   "id": "ah-194",
   "name": "Mystery Garden",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "194/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/194/high.webp"
  },
  {
   "id": "ah-195",
   "name": "N's PP Up",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "195/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/195/high.webp"
  },
  {
   "id": "ah-196",
   "name": "Night Stretcher",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "196/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/196/high.webp"
  },
  {
   "id": "ah-197",
   "name": "Nighttime Mine",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "197/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.25,
   "priceText": "$0.25",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/197/high.webp"
  },
  {
   "id": "ah-198",
   "name": "Poké Pad",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "198/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.46,
   "priceText": "$0.46",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/198/high.webp"
  },
  {
   "id": "ah-199",
   "name": "Premium Power Pro",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "199/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.13,
   "priceText": "$0.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/199/high.webp"
  },
  {
   "id": "ah-200",
   "name": "Surfer",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "200/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/200/high.webp"
  },
  {
   "id": "ah-201",
   "name": "Team Rocket's Archer",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "201/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/201/high.webp"
  },
  {
   "id": "ah-202",
   "name": "Team Rocket's Ariana",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "202/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.14,
   "priceText": "$0.14",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/202/high.webp"
  },
  {
   "id": "ah-203",
   "name": "Team Rocket's Factory",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "203/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/203/high.webp"
  },
  {
   "id": "ah-204",
   "name": "Team Rocket's Giovanni",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "204/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/204/high.webp"
  },
  {
   "id": "ah-205",
   "name": "Team Rocket's Great Ball",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "205/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.09,
   "priceText": "$0.09",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/205/high.webp"
  },
  {
   "id": "ah-206",
   "name": "Team Rocket's Hypnotizer",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "206/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.38,
   "priceText": "$0.38",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/206/high.webp"
  },
  {
   "id": "ah-207",
   "name": "Team Rocket's Petrel",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "207/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.38,
   "priceText": "$0.38",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/207/high.webp"
  },
  {
   "id": "ah-208",
   "name": "Team Rocket's Proton",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "208/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/208/high.webp"
  },
  {
   "id": "ah-209",
   "name": "Team Rocket's Transceiver",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "209/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.18,
   "priceText": "$0.18",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/209/high.webp"
  },
  {
   "id": "ah-210",
   "name": "Team Rocket's Watchtower",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "210/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.17,
   "priceText": "$0.17",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/210/high.webp"
  },
  {
   "id": "ah-211",
   "name": "Thick Scale",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "211/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.08,
   "priceText": "$0.08",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/211/high.webp"
  },
  {
   "id": "ah-212",
   "name": "Tool Scrapper",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "212/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.15,
   "priceText": "$0.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/212/high.webp"
  },
  {
   "id": "ah-213",
   "name": "Ultra Ball",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "213/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.16,
   "priceText": "$0.16",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/213/high.webp"
  },
  {
   "id": "ah-214",
   "name": "Urbain",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "214/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/214/high.webp"
  },
  {
   "id": "ah-215",
   "name": "Waitress",
   "variant": "Common",
   "set": "Ascended Heroes",
   "number": "215/217",
   "year": 2026,
   "rarity": "Common",
   "tier": 1,
   "price": 0.22,
   "priceText": "$0.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/215/high.webp"
  },
  {
   "id": "ah-216",
   "name": "Prism Energy",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "216/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.2,
   "priceText": "$0.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/216/high.webp"
  },
  {
   "id": "ah-217",
   "name": "Team Rocket's Energy",
   "variant": "Uncommon",
   "set": "Ascended Heroes",
   "number": "217/217",
   "year": 2026,
   "rarity": "Uncommon",
   "tier": 1,
   "price": 0.14,
   "priceText": "$0.14",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/217/high.webp"
  },
  {
   "id": "ah-218",
   "name": "Erika's Tangela",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "218/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 25.56,
   "priceText": "$25.56",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/218/high.webp"
  },
  {
   "id": "ah-219",
   "name": "Beautifly",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "219/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 7.9,
   "priceText": "$7.90",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/219/high.webp"
  },
  {
   "id": "ah-220",
   "name": "Dustox",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "220/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 4.27,
   "priceText": "$4.27",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/220/high.webp"
  },
  {
   "id": "ah-221",
   "name": "Budew",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "221/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 9.93,
   "priceText": "$9.93",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/221/high.webp"
  },
  {
   "id": "ah-222",
   "name": "Ethan's Magcargo",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "222/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 8.11,
   "priceText": "$8.11",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/222/high.webp"
  },
  {
   "id": "ah-223",
   "name": "Numel",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "223/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.07,
   "priceText": "$6.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/223/high.webp"
  },
  {
   "id": "ah-224",
   "name": "Salazzle",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "224/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 3.66,
   "priceText": "$3.66",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/224/high.webp"
  },
  {
   "id": "ah-225",
   "name": "Scorbunny",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "225/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 11.49,
   "priceText": "$11.49",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/225/high.webp"
  },
  {
   "id": "ah-226",
   "name": "Psyduck",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "226/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 2,
   "price": 102.15,
   "priceText": "$102.15",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/226/high.webp"
  },
  {
   "id": "ah-227",
   "name": "Snorunt",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "227/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.23,
   "priceText": "$6.23",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/227/high.webp"
  },
  {
   "id": "ah-228",
   "name": "Weavile",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "228/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 7.62,
   "priceText": "$7.62",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/228/high.webp"
  },
  {
   "id": "ah-229",
   "name": "Heliolisk",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "229/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 2.78,
   "priceText": "$2.78",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/229/high.webp"
  },
  {
   "id": "ah-230",
   "name": "Vikavolt",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "230/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 2.83,
   "priceText": "$2.83",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/230/high.webp"
  },
  {
   "id": "ah-231",
   "name": "Iono's Wattrel",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "231/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 10.59,
   "priceText": "$10.59",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/231/high.webp"
  },
  {
   "id": "ah-232",
   "name": "Marill",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "232/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 15.69,
   "priceText": "$15.69",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/232/high.webp"
  },
  {
   "id": "ah-233",
   "name": "Misdreavus",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "233/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.59,
   "priceText": "$6.59",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/233/high.webp"
  },
  {
   "id": "ah-234",
   "name": "Banette",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "234/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 12.55,
   "priceText": "$12.55",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/234/high.webp"
  },
  {
   "id": "ah-235",
   "name": "Togekiss",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "235/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.98,
   "priceText": "$6.98",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/235/high.webp"
  },
  {
   "id": "ah-236",
   "name": "Slurpuff",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "236/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 9.28,
   "priceText": "$9.28",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/236/high.webp"
  },
  {
   "id": "ah-237",
   "name": "Hop's Trevenant",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "237/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.27,
   "priceText": "$6.27",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/237/high.webp"
  },
  {
   "id": "ah-238",
   "name": "Team Rocket's Mimikyu",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "238/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 29.27,
   "priceText": "$29.27",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/238/high.webp"
  },
  {
   "id": "ah-239",
   "name": "Team Rocket's Dugtrio",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "239/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 15.04,
   "priceText": "$15.04",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/239/high.webp"
  },
  {
   "id": "ah-240",
   "name": "Hitmontop",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "240/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 7.9,
   "priceText": "$7.90",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/240/high.webp"
  },
  {
   "id": "ah-241",
   "name": "Medicham",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "241/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.57,
   "priceText": "$6.57",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/241/high.webp"
  },
  {
   "id": "ah-242",
   "name": "Carbink",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "242/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.13,
   "priceText": "$6.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/242/high.webp"
  },
  {
   "id": "ah-243",
   "name": "Mightyena",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "243/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 9.19,
   "priceText": "$9.19",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/243/high.webp"
  },
  {
   "id": "ah-244",
   "name": "Cynthia's Spiritomb",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "244/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 13.63,
   "priceText": "$13.63",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/244/high.webp"
  },
  {
   "id": "ah-245",
   "name": "Galarian Obstagoon",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "245/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 4.14,
   "priceText": "$4.14",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/245/high.webp"
  },
  {
   "id": "ah-246",
   "name": "Mawile",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "246/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 6.86,
   "priceText": "$6.86",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/246/high.webp"
  },
  {
   "id": "ah-247",
   "name": "Dreepy",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "247/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 11.67,
   "priceText": "$11.67",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/247/high.webp"
  },
  {
   "id": "ah-248",
   "name": "Drakloak",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "248/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 9.03,
   "priceText": "$9.03",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/248/high.webp"
  },
  {
   "id": "ah-249",
   "name": "Larry's Staraptor",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "249/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 4.87,
   "priceText": "$4.87",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/249/high.webp"
  },
  {
   "id": "ah-250",
   "name": "Fan Rotom",
   "variant": "Illustration rare",
   "set": "Ascended Heroes",
   "number": "250/217",
   "year": 2026,
   "rarity": "Illustration rare",
   "tier": 1,
   "price": 4.25,
   "priceText": "$4.25",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/250/high.webp"
  },
  {
   "id": "ah-251",
   "name": "Sprigatito ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "251/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 2.71,
   "priceText": "$2.71",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/251/high.webp"
  },
  {
   "id": "ah-252",
   "name": "Stunfisk ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "252/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 0.76,
   "priceText": "$0.76",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/252/high.webp"
  },
  {
   "id": "ah-253",
   "name": "Mega Audino ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "253/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 1.86,
   "priceText": "$1.86",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/253/high.webp"
  },
  {
   "id": "ah-254",
   "name": "Anthea & Concordia",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "254/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 1.23,
   "priceText": "$1.23",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/254/high.webp"
  },
  {
   "id": "ah-255",
   "name": "Black Belt's Training",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "255/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 1.23,
   "priceText": "$1.23",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/255/high.webp"
  },
  {
   "id": "ah-256",
   "name": "Boss's Orders",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "256/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 9.22,
   "priceText": "$9.22",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/256/high.webp"
  },
  {
   "id": "ah-257",
   "name": "Canari",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "257/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 3.64,
   "priceText": "$3.64",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/257/high.webp"
  },
  {
   "id": "ah-258",
   "name": "Cheren",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "258/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 0.87,
   "priceText": "$0.87",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/258/high.webp"
  },
  {
   "id": "ah-259",
   "name": "Counter Gain",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "259/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 0.74,
   "priceText": "$0.74",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/259/high.webp"
  },
  {
   "id": "ah-260",
   "name": "Glass Trumpet",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "260/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 0.75,
   "priceText": "$0.75",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/260/high.webp"
  },
  {
   "id": "ah-261",
   "name": "Jamming Tower",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "261/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 1.01,
   "priceText": "$1.01",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/261/high.webp"
  },
  {
   "id": "ah-262",
   "name": "N's PP Up",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "262/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 2.78,
   "priceText": "$2.78",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/262/high.webp"
  },
  {
   "id": "ah-263",
   "name": "Team Rocket's Transceiver",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "263/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 1.4,
   "priceText": "$1.40",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/263/high.webp"
  },
  {
   "id": "ah-264",
   "name": "Ultra Ball",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "264/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 8.07,
   "priceText": "$8.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/264/high.webp"
  },
  {
   "id": "ah-265",
   "name": "Mega Froslass ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "265/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 12.68,
   "priceText": "$12.68",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/265/high.webp"
  },
  {
   "id": "ah-266",
   "name": "Mega Eelektross ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "266/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 4.77,
   "priceText": "$4.77",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/266/high.webp"
  },
  {
   "id": "ah-267",
   "name": "Mega Diancie ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "267/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 8.97,
   "priceText": "$8.97",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/267/high.webp"
  },
  {
   "id": "ah-268",
   "name": "Mega Hawlucha ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "268/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 7.48,
   "priceText": "$7.48",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/268/high.webp"
  },
  {
   "id": "ah-269",
   "name": "Mega Gengar ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "269/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 2,
   "price": 73.05,
   "priceText": "$73.05",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/269/high.webp"
  },
  {
   "id": "ah-270",
   "name": "Mega Scrafty ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "270/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 1,
   "price": 5.82,
   "priceText": "$5.82",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/270/high.webp"
  },
  {
   "id": "ah-271",
   "name": "Mega Dragonite ex",
   "variant": "Ultra Rare",
   "set": "Ascended Heroes",
   "number": "271/217",
   "year": 2026,
   "rarity": "Ultra Rare",
   "tier": 2,
   "price": 56.4,
   "priceText": "$56.40",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/271/high.webp"
  },
  {
   "id": "ah-272",
   "name": "Mega Meganium ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "272/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 99.25,
   "priceText": "$99.25",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/272/high.webp"
  },
  {
   "id": "ah-273",
   "name": "Mega Emboar ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "273/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 71.99,
   "priceText": "$71.99",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/273/high.webp"
  },
  {
   "id": "ah-274",
   "name": "Mega Feraligatr ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "274/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 187.54,
   "priceText": "$187.54",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/274/high.webp"
  },
  {
   "id": "ah-275",
   "name": "Mega Froslass ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "275/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 87.86,
   "priceText": "$87.86",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/275/high.webp"
  },
  {
   "id": "ah-276",
   "name": "Pikachu ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "276/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 3,
   "price": 1360.6,
   "priceText": "$1,360.60",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/276/high.webp"
  },
  {
   "id": "ah-277",
   "name": "Pikachu ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "277/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 3,
   "price": 454.01,
   "priceText": "$454.01",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/277/high.webp"
  },
  {
   "id": "ah-278",
   "name": "Mega Eelektross ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "278/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 1,
   "price": 47.28,
   "priceText": "$47.28",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/278/high.webp"
  },
  {
   "id": "ah-279",
   "name": "Iono's Bellibolt ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "279/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 72.95,
   "priceText": "$72.95",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/279/high.webp"
  },
  {
   "id": "ah-280",
   "name": "Lillie's Clefairy ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "280/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 209.13,
   "priceText": "$209.13",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/280/high.webp"
  },
  {
   "id": "ah-281",
   "name": "Team Rocket's Mewtwo ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "281/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 3,
   "price": 424.94,
   "priceText": "$424.94",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/281/high.webp"
  },
  {
   "id": "ah-282",
   "name": "Mega Diancie ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "282/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 73.51,
   "priceText": "$73.51",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/282/high.webp"
  },
  {
   "id": "ah-283",
   "name": "Mega Hawlucha ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "283/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 72.2,
   "priceText": "$72.20",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/283/high.webp"
  },
  {
   "id": "ah-284",
   "name": "Mega Gengar ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "284/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 3,
   "price": 1444.8,
   "priceText": "$1,444.80",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/284/high.webp"
  },
  {
   "id": "ah-285",
   "name": "Mega Scrafty ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "285/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 75.4,
   "priceText": "$75.40",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/285/high.webp"
  },
  {
   "id": "ah-286",
   "name": "N's Zoroark ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "286/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 194.92,
   "priceText": "$194.92",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/286/high.webp"
  },
  {
   "id": "ah-287",
   "name": "Marnie's Grimmsnarl ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "287/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 80.43,
   "priceText": "$80.43",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/287/high.webp"
  },
  {
   "id": "ah-288",
   "name": "Fezandipiti ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "288/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 72.05,
   "priceText": "$72.05",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/288/high.webp"
  },
  {
   "id": "ah-289",
   "name": "Steven's Metagross ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "289/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 2,
   "price": 103.87,
   "priceText": "$103.87",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/289/high.webp"
  },
  {
   "id": "ah-290",
   "name": "Mega Dragonite ex",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "290/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 3,
   "price": 851.07,
   "priceText": "$851.07",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/290/high.webp"
  },
  {
   "id": "ah-291",
   "name": "Canari",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "291/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 1,
   "price": 44.85,
   "priceText": "$44.85",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/291/high.webp"
  },
  {
   "id": "ah-292",
   "name": "Iris's Fighting Spirit",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "292/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 1,
   "price": 37.25,
   "priceText": "$37.25",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/292/high.webp"
  },
  {
   "id": "ah-293",
   "name": "Surfer",
   "variant": "Special illustration rare",
   "set": "Ascended Heroes",
   "number": "293/217",
   "year": 2026,
   "rarity": "Special illustration rare",
   "tier": 1,
   "price": 28.79,
   "priceText": "$28.79",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/293/high.webp"
  },
  {
   "id": "ah-294",
   "name": "Mega Charizard Y ex",
   "variant": "Mega Hyper Rare",
   "set": "Ascended Heroes",
   "number": "294/217",
   "year": 2026,
   "rarity": "Mega Hyper Rare",
   "tier": 3,
   "price": 610.1,
   "priceText": "$610.10",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/294/high.webp"
  },
  {
   "id": "ah-295",
   "name": "Mega Dragonite ex",
   "variant": "Mega Hyper Rare",
   "set": "Ascended Heroes",
   "number": "295/217",
   "year": 2026,
   "rarity": "Mega Hyper Rare",
   "tier": 3,
   "price": 322.5,
   "priceText": "$322.50",
   "confidence": "High",
   "img": "https://assets.tcgdex.net/en/me/me02.5/295/high.webp"
  }
 ]
}
);
