/* ============================================================
   MEW MASTER SET — card data
   ------------------------------------------------------------
   To ADD a card: copy any line below, paste it, and edit it.
   Give every card a UNIQUE `id` (used to remember your checkmark).
   The site updates itself — no rebuild needed.

   tier:  1 = Bulk  (under $50)
          2 = Mid   ($50–300)
          3 = Grail ($300+)
   price:     number used for totals + sorting
   priceText: what shows on the card (can be a range)
   img:       official card art (Pokémon TCG API / TCGdex). Leave '' for none.
   Prices are raw / ungraded near-mint, snapshot 2026-06-25.
   ============================================================ */

window.MEW_CARDS = [
  { id:'battle-academy-032',         name:'Mew',               variant:'Mewtwo-stamped',            set:'Battle Academy',            number:'032/068',  year:2020, rarity:'Promo',                     tier:1, price:3.30,    priceText:'$3.30',         confidence:'High',   img:'img/battle-academy-mew.jpg' },
  { id:'hidden-fates-032',           name:'Mew',               variant:'Regular',                   set:'Hidden Fates',              number:'032/068',  year:2019, rarity:'Rare',                      tier:1, price:3.50,    priceText:'~$3.50',        confidence:'High',   img:'https://images.pokemontcg.io/sm115/32_hires.png' },
  { id:'celebrations-011',           name:'Mew',               variant:'Regular',                   set:'Celebrations',              number:'011/025',  year:2021, rarity:'Holo Rare',                 tier:1, price:4.86,    priceText:'$4.86',         confidence:'High',   img:'https://images.pokemontcg.io/cel25/11_hires.png' },
  { id:'fusion-strike-mewv-113',     name:'Mew V',             variant:'Regular',                   set:'Fusion Strike',             number:'113/264',  year:2021, rarity:'Ultra Rare',                tier:1, price:4.93,    priceText:'$4.93',         confidence:'High',   img:'https://images.pokemontcg.io/swsh8/113_hires.png' },
  { id:'crown-zenith-mewv-060',      name:'Mew V',             variant:'Regular',                   set:'Crown Zenith',              number:'060/159',  year:2023, rarity:'Ultra Rare',                tier:1, price:7.50,    priceText:'~$7.50',        confidence:'High',   img:'https://images.pokemontcg.io/swsh12pt5/60_hires.png' },
  { id:'sv151-mewex-151',            name:'Mew ex',            variant:'Double Rare',               set:'Scarlet & Violet 151',      number:'151/165',  year:2023, rarity:'Double Rare',               tier:1, price:9.93,    priceText:'$9.93',         confidence:'High',   img:'https://images.pokemontcg.io/sv3pt5/151_hires.png' },
  { id:'wizards-promo-8',            name:'Mew',               variant:'Classic promo',             set:'Wizards Black Star Promos', number:'8',        year:1999, rarity:'Promo',                     tier:1, price:10.68,   priceText:'$10.68',        confidence:'High',   img:'https://images.pokemontcg.io/basep/8_hires.png' },
  { id:'unbroken-bonds-076',         name:'Mew',               variant:'Regular',                   set:'Unbroken Bonds',            number:'76/214',   year:2019, rarity:'Rare Holo',                 tier:1, price:14.66,   priceText:'$14.66',        confidence:'High',   img:'https://images.pokemontcg.io/sm10/76_hires.png' },
  { id:'fates-collide-029',          name:'Mew',               variant:'Regular',                   set:'XY Fates Collide',          number:'29/124',   year:2016, rarity:'Holo Rare',                 tier:1, price:17,      priceText:'~$17',          confidence:'High',   img:'https://images.pokemontcg.io/xy10/29_hires.png' },
  { id:'fusion-strike-mewvmax-114',  name:'Mew VMAX',          variant:'Regular',                   set:'Fusion Strike',             number:'114/264',  year:2021, rarity:'VMAX',                      tier:1, price:17.25,   priceText:'$17.25',        confidence:'High',   img:'https://images.pokemontcg.io/swsh8/114_hires.png' },
  { id:'lost-origin-mewvmax-tg30',   name:'Mew VMAX',          variant:'Trainer Gallery',           set:'Lost Origin',               number:'TG30/TG30',year:2022, rarity:'Trainer Gallery Secret',    tier:1, price:19,      priceText:'~$19',          confidence:'High',   img:'https://images.pokemontcg.io/swsh11tg/TG30_hires.png' },
  { id:'evolutions-053',             name:'Mew',               variant:'Regular',                   set:'XY Evolutions',             number:'53/108',   year:2016, rarity:'Holo Rare',                 tier:1, price:25,      priceText:'~$25',          confidence:'High',   img:'https://images.pokemontcg.io/xy12/53_hires.png' },
  { id:'sm-promo-215',               name:'Mew',               variant:'Holo promo',                set:'SM Black Star Promos',      number:'SM215',    year:2019, rarity:'Promo Holo',                tier:1, price:27,      priceText:'~$27',          confidence:'High',   img:'https://images.pokemontcg.io/smp/SM215_hires.png' },
  { id:'fusion-strike-mewv-250',     name:'Mew V',             variant:'Full Art',                  set:'Fusion Strike',             number:'250/264',  year:2021, rarity:'Ultra Rare',                tier:1, price:29.87,   priceText:'$29.87',        confidence:'High',   img:'https://images.pokemontcg.io/swsh8/250_hires.png' },
  { id:'sv151-mewex-205',            name:'Mew ex',            variant:'Gold (Hyper Rare)',         set:'Scarlet & Violet 151',      number:'205/165',  year:2023, rarity:'Hyper Rare',                tier:1, price:35,      priceText:'~$35',          confidence:'High',   img:'https://images.pokemontcg.io/sv3pt5/205_hires.png' },
  { id:'paldean-fates-mewex-216',    name:'Mew ex',            variant:'Shiny',                     set:'Paldean Fates',             number:'216/091',  year:2024, rarity:'Shiny Ultra Rare',          tier:1, price:40.54,   priceText:'~$40.54',       confidence:'High',   img:'https://images.pokemontcg.io/sv4pt5/216_hires.png' },
  { id:'darkness-ablaze-jumbo-069',  name:'Mew V',             variant:'Jumbo / oversized',         set:'Darkness Ablaze (jumbo)',   number:'69',       year:2020, rarity:'Oversized Promo',           tier:1, price:43,      priceText:'~$43',          confidence:'Medium', img:'https://images.pokemontcg.io/swsh3/69_hires.png' },
  { id:'sv151-mewex-193',            name:'Mew ex',            variant:'Full Art',                  set:'Scarlet & Violet 151',      number:'193/165',  year:2023, rarity:'Ultra Rare',                tier:1, price:44.59,   priceText:'$44.59',        confidence:'High',   img:'https://images.pokemontcg.io/sv3pt5/193_hires.png' },
  { id:'celebrations-025',           name:'Mew',               variant:'Secret (shiny full-art)',   set:'Celebrations',              number:'025/025',  year:2021, rarity:'Secret Rare',               tier:2, price:58,      priceText:'~$58',          confidence:'High',   img:'https://images.pokemontcg.io/cel25/25_hires.png' },
  { id:'crown-zenith-gg10',          name:'Mew',               variant:'Galarian Gallery',          set:'Crown Zenith',              number:'GG10/GG70',year:2023, rarity:'Ultra Rare',                tier:2, price:73,      priceText:'~$73',          confidence:'Medium', img:'https://images.pokemontcg.io/swsh12pt5gg/GG10_hires.png' },
  { id:'dragons-exalted-mewex-046',  name:'Mew-EX',            variant:'Regular',                   set:'Dragons Exalted',           number:'46/124',   year:2012, rarity:'Rare Holo EX',              tier:2, price:82.76,   priceText:'~$83',          confidence:'Medium', img:'https://images.pokemontcg.io/bw6/46_hires.png' },
  { id:'xy-promo-192',               name:'Mew',               variant:'Holo promo',                set:'XY Black Star Promos',      number:'XY192',    year:2017, rarity:'Promo Holo',                tier:2, price:90,      priceText:'~$90',          confidence:'High',   img:'https://images.pokemontcg.io/xyp/XY192_hires.png' },
  { id:'pop-series-4-004',           name:'Mew',               variant:'Regular',                   set:'POP Series 4',              number:'4/17',     year:2006, rarity:'Holo Rare',                 tier:2, price:93,      priceText:'~$93',          confidence:'High',   img:'https://images.pokemontcg.io/pop4/4_hires.png' },
  { id:'ancient-mew-promo',          name:'Ancient Mew',       variant:'Movie promo',               set:'Pokémon Promo',             number:'—',        year:2000, rarity:'Promo',                     tier:2, price:100,     priceText:'~$80–112',      confidence:'Medium', img:'img/ancient-mew.jpg' },
  { id:'fusion-strike-mewv-251',     name:'Mew V',             variant:'Alternate Art',             set:'Fusion Strike',             number:'251/264',  year:2021, rarity:'Alt Art Secret',            tier:2, price:102.86,  priceText:'$102.86',       confidence:'High',   img:'https://images.pokemontcg.io/swsh8/251_hires.png' },
  { id:'fusion-strike-mewvmax-268',  name:'Mew VMAX',          variant:'Secret (rainbow)',          set:'Fusion Strike',             number:'268/264',  year:2021, rarity:'Secret Rare',               tier:2, price:109,     priceText:'~$109',         confidence:'High',   img:'https://images.pokemontcg.io/swsh8/268_hires.png' },
  { id:'sv-promo-svp053',            name:'Mew ex',            variant:'Etched alt-art promo',      set:'SV Promo (151 UPC)',        number:'SVP053',   year:2023, rarity:'Black Star Promo',          tier:2, price:111,     priceText:'~$111',         confidence:'High',   img:'https://images.pokemontcg.io/svp/53_hires.png' },
  { id:'shining-legends-040',        name:'Shining Mew',       variant:'Shining',                   set:'Shining Legends',           number:'40/73',    year:2017, rarity:'Rare Shining',              tier:2, price:114.46,  priceText:'~$114',         confidence:'High',   img:'https://images.pokemontcg.io/sm35/40_hires.png' },
  { id:'unified-minds-mewtwomew-071',name:'Mewtwo & Mew-GX',   variant:'Regular GX',                set:'Unified Minds',             number:'71/236',   year:2019, rarity:'Rare Holo GX',              tier:2, price:118.70,  priceText:'~$118.70',      confidence:'High',   img:'https://images.pokemontcg.io/sm11/71_hires.png' },
  { id:'wizards-promo-9',            name:'Mew',               variant:'Bubble Mew (holo)',         set:'Wizards Black Star Promos', number:'9',        year:2000, rarity:'Promo Holo',                tier:2, price:119.35,  priceText:'~$119.35',      confidence:'High',   img:'https://images.pokemontcg.io/basep/9_hires.png' },
  { id:'xy-promo-110',               name:'Mew',               variant:'Holo promo',                set:'XY Black Star Promos',      number:'XY110',    year:2016, rarity:'Promo Holo',                tier:2, price:125,     priceText:'~$125',         confidence:'Medium', img:'https://images.pokemontcg.io/xyp/XY110_hires.png' },
  { id:'wizards-promo-47',           name:'Mew',               variant:'League promo',              set:'Wizards Black Star Promos', number:'47',       year:2002, rarity:'Promo',                     tier:2, price:133.59,  priceText:'$133.59',       confidence:'High',   img:'https://images.pokemontcg.io/basep/47_hires.png' },
  { id:'pop-series-5-003',           name:'Mew',               variant:'Delta Species',             set:'POP Series 5',              number:'3/17',     year:2007, rarity:'Holo Rare',                 tier:2, price:145,     priceText:'~$145',         confidence:'Medium', img:'https://images.pokemontcg.io/pop5/3_hires.png' },
  { id:'unified-minds-mewtwomew-222',name:'Mewtwo & Mew-GX',   variant:'Full Art',                  set:'Unified Minds',             number:'222/236',  year:2019, rarity:'Full Art Ultra Rare',       tier:2, price:146,     priceText:'~$146',         confidence:'Medium', img:'https://images.pokemontcg.io/sm11/222_hires.png' },
  { id:'holon-phantoms-111',         name:'Mew',               variant:'Secret Rare (non-ex)',      set:'EX Holon Phantoms',         number:'111/110',  year:2006, rarity:'Secret Rare Holo',          tier:2, price:172,     priceText:'~$172',         confidence:'High',   img:'https://images.pokemontcg.io/ex13/111_hires.png' },
  { id:'xy-promo-126',               name:'Mew-EX',            variant:'Full Art promo',            set:'XY Black Star Promos',      number:'XY126',    year:2015, rarity:'Promo Ultra Rare',          tier:2, price:175,     priceText:'~$175',         confidence:'High',   img:'https://images.pokemontcg.io/xyp/XY126_hires.png' },
  { id:'sm-promo-191',               name:'Mewtwo & Mew-GX',   variant:'Full Art promo',            set:'SM Black Star Promos',      number:'SM191',    year:2019, rarity:'Promo Full Art UR',         tier:2, price:180,     priceText:'~$180',         confidence:'High',   img:'https://images.pokemontcg.io/smp/SM191_hires.png' },
  { id:'legendary-treasures-rc24',   name:'Mew-EX',            variant:'Full Art (Radiant Coll.)',  set:'Legendary Treasures',       number:'RC24/RC25',year:2013, rarity:'Full Art Ultra Rare',       tier:2, price:182,     priceText:'~$182',         confidence:'Medium', img:'https://images.pokemontcg.io/bw11/RC24_hires.png' },
  { id:'legend-maker-010',           name:'Mew',               variant:'Non-ex holo',               set:'EX Legend Maker',           number:'10/92',    year:2006, rarity:'Holo Rare',                 tier:2, price:184,     priceText:'~$184',         confidence:'High',   img:'https://images.pokemontcg.io/ex12/10_hires.png' },
  { id:'legend-maker-088',           name:'Mew ex',            variant:'Regular',                   set:'EX Legend Maker',           number:'88/92',    year:2006, rarity:'Rare Holo ex',              tier:2, price:200,     priceText:'~$200',         confidence:'Medium', img:'https://images.pokemontcg.io/ex12/88_hires.png' },
  { id:'fusion-strike-mewvmax-269',  name:'Mew VMAX',          variant:'Alt Art Secret (chibi)',    set:'Fusion Strike',             number:'269/264',  year:2021, rarity:'Alt Art Secret',            tier:2, price:273.75,  priceText:'$273.75',       confidence:'High',   img:'https://images.pokemontcg.io/swsh8/269_hires.png' },
  { id:'pokemon-rumble-010',         name:'Mew',               variant:'Game promo',                set:'Pokémon Rumble',            number:'10/16',    year:2009, rarity:'Promo',                     tier:3, price:300,     priceText:'~$300',         confidence:'High',   img:'https://images.pokemontcg.io/ru1/10_hires.png' },
  { id:'bw-promo-98',                name:'Mew',               variant:'Holo promo',                set:'BW Black Star Promos',      number:'BW98',     year:2012, rarity:'Promo Holo',                tier:3, price:300,     priceText:'~$300',         confidence:'High',   img:'https://images.pokemontcg.io/bwp/BW98_hires.png' },
  { id:'hs-triumphant-097',          name:'Mew Prime',         variant:'Prime',                     set:'HS Triumphant',             number:'97/102',   year:2011, rarity:'Prime',                     tier:3, price:331.34,  priceText:'~$331',         confidence:'Medium', img:'https://images.pokemontcg.io/hgss4/97_hires.png' },
  { id:'southern-islands-001',       name:'Mew',               variant:'Regular (holo)',            set:'Southern Islands',          number:'1/18',     year:2001, rarity:'Holo Rare',                 tier:3, price:360,     priceText:'~$360',         confidence:'Medium', img:'https://images.pokemontcg.io/si1/1_hires.png' },
  { id:'unified-minds-mewtwomew-242',name:'Mewtwo & Mew-GX',   variant:'Rainbow Secret',            set:'Unified Minds',             number:'242/236',  year:2019, rarity:'Rainbow Secret Rare',       tier:3, price:385,     priceText:'~$385',         confidence:'Medium', img:'https://images.pokemontcg.io/sm11/242_hires.png' },
  { id:'expedition-019',             name:'Mew',               variant:'Regular (holo)',            set:'Expedition Base Set',       number:'19/165',   year:2002, rarity:'Rare Holo',                 tier:3, price:412,     priceText:'~$412',         confidence:'Medium', img:'https://images.pokemontcg.io/ecard1/19_hires.png' },
  { id:'dragons-exalted-mewex-120',  name:'Mew-EX',            variant:'Full Art Secret',           set:'Dragons Exalted',           number:'120/124',  year:2012, rarity:'Full Art Ultra Rare',       tier:3, price:423.51,  priceText:'~$424',         confidence:'Medium', img:'https://images.pokemontcg.io/bw6/120_hires.png' },
  { id:'holon-phantoms-100',         name:'Mew ex',            variant:'Regular',                   set:'EX Holon Phantoms',         number:'100/110',  year:2006, rarity:'Rare Holo ex',              tier:3, price:512.44,  priceText:'~$512',         confidence:'High',   img:'https://images.pokemontcg.io/ex13/100_hires.png' },
  { id:'paldean-fates-mewex-232',    name:'Mew ex',            variant:'Special Illustration Rare', set:'Paldean Fates',             number:'232/091',  year:2024, rarity:'Special Illustration Rare', tier:3, price:850,     priceText:'~$850',         confidence:'High',   img:'https://images.pokemontcg.io/sv4pt5/232_hires.png' },
  { id:'dragon-frontiers-101',       name:'Mew ☆ δ Gold Star', variant:'Gold Star (delta)',         set:'EX Dragon Frontiers',       number:'101/101',  year:2006, rarity:'Gold Star UR',              tier:3, price:2200,    priceText:'~$1,630–2,750', confidence:'Medium', img:'https://images.pokemontcg.io/ex15/101_hires.png' },
];
